[Theme]
Current=breeze
CursorTheme=breeze_cursors
CursorSize=24
Font=JetBrainsMono Nerd Font

[Wayland]
SessionDir=/usr/local/share/wayland-sessions

[Users]
RememberLastSession=true
RememberLastUser=true
